Nc 18 add a blog section module 3.3. create a public page for blog
germanngc/ninacodemx pull request #5
Opened 2024-06-19 22:54 UTC by MaxMancera1

Se crearon archivos articles, cambio en rutas, ejecutar `php artisan route:cache` y aplicar `php artisan migrate`

2024-06-19 23:21 UTC, Deividisi26 approved these changes
LGTM

2024-06-20 23:10 UTC, germanngc requested changes
Apart from the code suggestions, you need to create a few more files:

### Create a articles_slug.blade.php

Use as example the bellow file:
`resources/views/livewire/public/articles_slug.blade.php`

### Add translation language files

As you can notice in multiple parts of the files you created, there are some portions of code as `__('mainmenu.articles')` this can be fixed by adding a value `articles` in the next two files:

`lang/es/mainmenu.php` and `lang/en/mainmenu.php`

For the translations that looks like `__('pages/articles.hero.h1')` you will need to create two files:

`lang/es/pages/articles.php` and `lang/en/pages/articles.php`

2024-06-20 23:10 UTC, germanngc commented on app/Livewire/Public/Articles.php
> +            $Article = \App\Models\Article::orderBy('title')->get();
Change to plural

```suggestion
            $Articles = \App\Models\Article::orderBy('title')->get();
```

2024-06-20 23:10 UTC, germanngc commented on app/Livewire/Public/Articles.php
> +        return view('livewire.public.articles' . ($this->slug ? '_slug' : ''), ['articles' => $Article])
Change to plural

```suggestion
        return view('livewire.public.articles' . ($this->slug ? '_slug' : ''), ['articles' => $Articles])
```

2024-06-24 18:06 UTC, germanngc approved these changes
🚀

2024-06-24 18:35 UTC, germanngc approved these changes
re approved 🔥

2024-06-24 18:35 UTC, merged