Fix to languages
germanngc/ninacodemx pull request #9
Opened 2024-06-26 06:34 UTC by germanngc

Removed all the Cookie language set and moved into SetLocale middleware created by @MaxMancera1 

This will require to clear the views and routes:

```bash
docker exec ninacodemx-app php artisan route:clear
docker exec ninacodemx-app php artisan view:clear
```

2024-06-26 17:15 UTC, MaxMancera1 requested changes

2024-06-26 17:15 UTC, MaxMancera1 commented on lang/es/pages/articles.php
> +		'h2' => 'Ecneuntra información relevante para tu negocio.',
```suggestion
		'h2' => 'Encuentra información relevante para tu negocio.',
```

2024-06-27 04:05 UTC, germanngc reviewed
Self review

2024-06-29 14:55 UTC, germanngc reviewed
Self review

2024-06-29 16:25 UTC, MaxMancera1 approved these changes
CHECKED

2024-06-29 16:57 UTC, merged